In [1]:
import pandas as pd

In [3]:
# Load the data
df = pd.read_csv('annual_time_series_with_airports&airlines.csv')

# Perform groupby operation and calculate the yearly totals
grouped = df.groupby(['AIRLINE_ID', 'AIRCRAFT_TYPE'])['2019', '2020', '2021', '2022'].sum().reset_index()

# Drop duplicate rows for non-aggregate columns and keep the first one
non_aggregate = df[['AIRLINE_ID', 'AIRCRAFT_TYPE', 'ORIGIN_STATE_ABR', 'CODE', 'NAME', 'UNIQUE_CARRIER_NAME', 'Description']].drop_duplicates(subset=['AIRLINE_ID', 'AIRCRAFT_TYPE'])

# Merge the grouped dataframe with the non-aggregate dataframe
merged = pd.merge(non_aggregate, grouped, on=['AIRLINE_ID', 'AIRCRAFT_TYPE'])

# Reorder the columns
merged = merged[['AIRLINE_ID', 'UNIQUE_CARRIER_NAME', 'AIRCRAFT_TYPE', 'Description', '2019', '2020', '2021', '2022']]

# Save the output to a single file
merged.to_csv('annual_time_series_airlines&actypes.csv', index=False)

C:\Users\Juhana\AppData\Local\Temp\ipykernel_18936\2573546233.py:5: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  grouped = df.groupby(['AIRLINE_ID', 'AIRCRAFT_TYPE'])['2019', '2020', '2021', '2022'].sum().reset_index()

In [4]:
merged

,AIRLINE_ID,UNIQUE_CARRIER_NAME,AIRCRAFT_TYPE,Description,2019,2020,2021,2022
0,19790.0,Delta Air Lines Inc.,339,Airbus Industrie A330-900,14.0,6.0,509.0,454.0
1,19790.0,Delta Air Lines Inc.,359,Airbus Industrie A350-900,29.0,61.0,763.0,1307.0
2,21253.0,"Multi-Aero, Inc. d/b/a Air Choice One",415,Cessna C208B/Grand Caravan,6376.0,5852.0,2832.0,911.0
3,21599.0,Boutique Air,479,Pilatus PC-12,17537.0,13640.0,7324.0,4644.0
4,20500.0,GoJet Airlines LLC d/b/a United Express,530,Bombardier CRJ550,4609.0,32057.0,58149.0,50833.0
...,...,...,...,...,...,...,...,...
180,22080.0,Breeze Aviation Group DBA Breeze,724,A220-300 BD-500-1A11,0.0,0.0,0.0,3410.0
181,22080.0,Breeze Aviation Group DBA Breeze,617,Boeing 737-400,0.0,0.0,0.0,2.0
182,22080.0,Breeze Aviation Group DBA Breeze,694,Airbus Industrie A320-100/200,0.0,0.0,0.0,51.0
183,21618.0,"Southern Airways Express, dba Mokulele Airlines",479,Pilatus PC-12,0.0,0.0,0.0,340.0
184,21894.0,"ADVANCED AIR, LLC",609,Bombardier BD-100-1A10 Challenger 300,0.0,0.0,0.0,1.0