In [1]:
import pandas as pd

In [2]:
!dir

 Volume in drive C has no label.
 Volume Serial Number is 322A-B5F7

 Directory of c:\Users\Juhana\Desktop\Masters_New\time_series_airlines&airports&actypes\annual_combos

06/09/2023  07:39 AM    <DIR>          .
06/09/2023  07:39 AM    <DIR>          ..
05/29/2023  04:52 PM             1,516 AIRCRAFT_FAMILY.csv
06/08/2023  10:21 AM            15,800 annual_time_series_actypes&airlines.csv
06/08/2023  11:50 AM            13,953 annual_time_series_airlines&actypes.csv
06/08/2023  10:50 AM           482,967 annual_time_series_by_actypes@airports.csv
06/08/2023  10:44 AM           367,133 annual_time_series_by_airlines@airports.csv
06/08/2023  10:51 AM            10,287 groupby_annual_actypes&airlines.ipynb
06/08/2023  10:10 AM            11,343 groupby_annual_actypes&airports.ipynb
06/08/2023  10:19 AM            10,288 groupby_annual_airlines&actypes.ipynb
06/08/2023  09:07 AM            12,645 groupby_annual_airlines&airports.ipynb
06/09/2023  07:38 AM            25,782 Unite_combos&families.ipynb
              10 File(s)        951,714 bytes
               2 Dir(s)  87,414,140,928 bytes free

In [12]:
df = pd.read_csv('annual_time_series_actypes&airlines.csv')

In [4]:
df2 = pd.read_csv('AIRCRAFT_FAMILY.csv')

In [13]:
df.columns

Index(['AIRCRAFT_TYPE', 'Description', 'AIRLINE_ID', 'UNIQUE_CARRIER_NAME',
       '2019', '2020', '2021', '2022'],
      dtype='object')

In [6]:
df2.columns

Index(['AIRCRAFT_TYPE', 'AIRCRAFT_FAMILY'], dtype='object')

In [14]:
merged_df = df.merge(df2, on='AIRCRAFT_TYPE')

In [17]:
merged_df = merged_df[['AIRLINE_ID', 'UNIQUE_CARRIER_NAME', 'AIRCRAFT_TYPE', 'Description', 'AIRCRAFT_FAMILY', '2019', '2020', '2021', '2022']]

In [18]:
merged_df

,AIRLINE_ID,UNIQUE_CARRIER_NAME,AIRCRAFT_TYPE,Description,AIRCRAFT_FAMILY,2019,2020,2021,2022
0,19790.0,Delta Air Lines Inc.,339,Airbus Industrie A330-900,Airbus A330,14.0,6.0,509.0,454.0
1,19790.0,Delta Air Lines Inc.,359,Airbus Industrie A350-900,Airbus A350,29.0,61.0,763.0,1307.0
2,21253.0,"Multi-Aero, Inc. d/b/a Air Choice One",415,Cessna C208B/Grand Caravan,Single turboprop,6376.0,5852.0,2832.0,911.0
3,22081.0,"Tailwind Air, LLC",415,Cessna C208B/Grand Caravan,Single turboprop,0.0,0.0,11.0,82.0
4,21618.0,"Southern Airways Express, dba Mokulele Airlines",415,Cessna C208B/Grand Caravan,Single turboprop,0.0,0.0,0.0,13084.0
...,...,...,...,...,...,...,...,...,...
180,21492.0,"Eastern Airlines f/k/a Dynamic Airways, LLC",625,Boeing 767-200/ER/EM,Boeing 767,0.0,2.0,0.0,0.0
181,21894.0,"ADVANCED AIR, LLC",449,Dornier 328,Dornier 328 Jet,0.0,0.0,132.0,576.0
182,22080.0,Breeze Aviation Group DBA Breeze,748,Embraer EMB195,Embraer E-jet,0.0,0.0,1765.0,3788.0
183,22080.0,Breeze Aviation Group DBA Breeze,617,Boeing 737-400,Boeing 737,0.0,0.0,0.0,2.0
184,21894.0,"ADVANCED AIR, LLC",609,Bombardier BD-100-1A10 Challenger 300,Bombardier CRJ,0.0,0.0,0.0,1.0

In [19]:
merged_df.to_csv('annual_time_series_actypes&airlines_with_ACfamily.csv', index=False)

In [10]:

merged_df.columns

Index(['AIRCRAFT_TYPE', 'Description', '2019', '2020', '2021', '2022',
       'AIRCRAFT_FAMILY'],
      dtype='object')

In [9]:
families2_df = merged_df.groupby('AIRCRAFT_FAMILY')['2019', '2020', '2021', '2022'].sum().reset_index()

C:\Users\Juhana\AppData\Local\Temp\ipykernel_20096\743207513.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  families2_df = merged_df.groupby('AIRCRAFT_FAMILY')['2019', '2020', '2021', '2022'].sum().reset_index()

In [11]:
families2_df.to_csv('annual_time_series_by_ACfamily@above10K.csv', index=False)

In [12]:
families_df

         AIRCRAFT_FAMILY     2019     2020     2021     2022
0              ATR-42/72     2126     5878     9611     9204
1            Airbus A220    19951    27847    52668    91865
2       Airbus A319/A320  1146609   695059   908996  1110826
3            Airbus A321   507047   324350   503919   606199
4            Airbus A330     9718     5036    13095    10353
5            Airbus A350       29       61      763     1307
6             Boeing 717   152286    86742    87244   120106
7             Boeing 737  2371045  1446263  1784617  2145565
8         Boeing 737 Max    14397        6    91290   151977
9             Boeing 757   176586    83657   104780   128183
10            Boeing 767    18078    13855    35910    23503
11            Boeing 777    19595    10977    23716    21606
12            Boeing 787     8816     7899    12067    10858
13        Bombardier CRJ  1483402   909586  1138587   994431
14          Business jet        7        0        0        0
15                Dash 8    73212    49321    56923    43261
16       Dornier 328 Jet     2865     1520     2727     5061
17         Embraer E-jet  1008618   677693   978053   980063
18           Embraer ERJ   579173   278245   294271   265860
19            Helicopter      376      178      312      732
20             MD-series   211118    31195        0        0
21      Single turboprop    95664    74059    63323    67826
22  Small twin turboprop   100671    71933    86328    74110

In [23]:
families_df.to_csv('annual_time_series_by_acfamily_at_EXCL_airports.csv', index=False)

In [24]:
# Step 1: Calculate total for 2022
total_2022 = families_df['2022'].sum()

# Step 2: Filter data for specific aircraft families and calculate 2022 totals
specific_families = ['Airbus A319/A320', 'Airbus A321', 'Boeing 737', 'Boeing 737 Max']
specific_totals = families_df[families_df['AIRCRAFT_FAMILY'].isin(specific_families)].groupby('AIRCRAFT_FAMILY')['2022'].sum()

# Step 3: Calculate total for 'OTHER'
other_total = total_2022 - specific_totals.sum()

# Step 4: Calculate percentage shares
percentage_shares = (specific_totals / total_2022) * 100
percentage_shares.loc['OTHER'] = (other_total / total_2022) * 100

# Convert to dataframe and reset index
percentage_shares_df = percentage_shares.reset_index()
percentage_shares_df.columns = ['AIRCRAFT_FAMILY', '2022_PERCENTAGE_SHARE']

print(percentage_shares_df)

    AIRCRAFT_FAMILY  2022_PERCENTAGE_SHARE
0  Airbus A319/A320              16.185966
1       Airbus A321               8.832991
2        Boeing 737              31.263260
3    Boeing 737 Max               2.214473
4             OTHER              41.503310

In [25]:
percentage_shares_df.to_csv('pct_shares_by_acfamily_in_2022.csv', index=False)

In [26]:
# Step 1: Calculate total for 2022
total_2019 = families_df['2019'].sum()

# Step 2: Filter data for specific aircraft families and calculate 2022 totals
specific_families = ['Airbus A319/A320', 'Airbus A321', 'Boeing 737', 'Boeing 737 Max']
specific_totals = families_df[families_df['AIRCRAFT_FAMILY'].isin(specific_families)].groupby('AIRCRAFT_FAMILY')['2019'].sum()

# Step 3: Calculate total for 'OTHER'
other_total = total_2019 - specific_totals.sum()

# Step 4: Calculate percentage shares
percentage_shares = (specific_totals / total_2019) * 100
percentage_shares.loc['OTHER'] = (other_total / total_2019) * 100

# Convert to dataframe and reset index
percentage_shares_df = percentage_shares.reset_index()
percentage_shares_df.columns = ['AIRCRAFT_FAMILY', '2019_PERCENTAGE_SHARE']

print(percentage_shares_df)

    AIRCRAFT_FAMILY  2019_PERCENTAGE_SHARE
0  Airbus A319/A320              14.330124
1       Airbus A321               6.336987
2        Boeing 737              29.632917
3    Boeing 737 Max               0.179931
4             OTHER              49.520040

In [27]:
percentage_shares_df.to_csv('pct_shares_by_acfamily_in_2019.csv', index=False)