In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('above10K_airports_list.csv')

In [4]:
df2 = pd.read_csv('time_series_quarterly_deps_airport.csv')

In [5]:
df2

,ORIGIN_AIRPORT_ID,CODE,ORIGIN_STATE_ABR_x,NAME,LOCATION,ORIGIN_STATE_ABR_y,1Q2019,2Q2019,3Q2019,4Q2019,...,3Q2020,4Q2020,1Q2021,2Q2021,3Q2021,4Q2021,1Q2022,2Q2022,3Q2022,4Q2022
0,10005,05A,AK,Little Squaw Airport,Little Squaw,AK,1.0,0.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,10006,06A,AK,Kizhuyak Bay,Kizhuyak,AK,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,0.0,0.0
2,10011,GCW,AZ,Grand Canyon West,Peach Springs,AZ,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,8.0,18.0,21.0,11.0
3,10039,A26,AK,Ivotuk Airstrip,Ivotuk,AK,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN
4,10042,A29,AK,Kiluda Bay Airport,Kiluda Bay,AK,1.0,0.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
808,16869,XWA,ND,Williston Basin International,Williston,ND,0.0,0.0,0.0,405.0,...,96.0,178.0,172.0,209.0,378.0,373.0,314.0,347.0,449.0,371.0
809,16879,T4X,TX,Llano Municipal,Llano,TX,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,25.0,0.0
810,16923,1AK,AK,Mertarvik Quarry Road Landing Strip,Mertarvik,AK,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,15.0,15.0
811,16929,2AK,AK,Deer Park Airport,Deer Park,AK,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,0.0,2.0,7.0,3.0,0.0,3.0,1.0
812,16954,BNH,MA,Boston Harbor Seaplane Base,Boston,MA,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,0.0,0.0,40.0,6.0,126.0,120.0,41.0

In [32]:
#df2.columns

In [6]:
# Select the relevant columns from df2
df2_selected = df2[['ORIGIN_AIRPORT_ID', '1Q2019', '2Q2019', '3Q2019', '4Q2019', '1Q2020', '2Q2020', '3Q2020',
       '4Q2020', '1Q2021', '2Q2021', '3Q2021', '4Q2021', '1Q2022', '2Q2022',
       '3Q2022', '4Q2022']]

# Merge df with the selected columns from df2
merged_df = df.merge(df2_selected, on='ORIGIN_AIRPORT_ID', how='left')

In [7]:
merged_df

,ORIGIN_AIRPORT_ID,CODE,ORIGIN_STATE_ABR,NAME,LOCATION,category,EAS,diff,pct_change,change_category,...,3Q2020,4Q2020,1Q2021,2Q2021,3Q2021,4Q2021,1Q2022,2Q2022,3Q2022,4Q2022
0,10135,ABE,PA,Lehigh Valley International,Allentown/Bethlehem/Easton,100k-1 million,no,loss,-21.7,at least -20%,...,736.0,1001.0,1020.0,1523.0,1385.0,1384.0,1169.0,1492.0,1337.0,1093.0
1,10136,ABI,TX,Abilene Regional,Abilene,10k-100k,no,loss,-16.8,at least -10%,...,384.0,532.0,474.0,672.0,745.0,503.0,414.0,538.0,540.0,432.0
2,10140,ABQ,NM,Albuquerque International Sunport,Albuquerque,1-5 million,no,loss,-19.7,at least -10%,...,3821.0,3530.0,3290.0,4633.0,5645.0,5502.0,5061.0,5527.0,5860.0,5886.0
3,10141,ABR,SD,Aberdeen Regional,Aberdeen,10k-100k,yes,loss,-5.4,less than -10%,...,187.0,206.0,181.0,183.0,187.0,203.0,178.0,181.0,184.0,157.0
4,10146,ABY,GA,Southwest Georgia Regional,Albany,10k-100k,no,loss,-5.1,less than -10%,...,151.0,257.0,254.0,270.0,278.0,249.0,221.0,262.0,233.0,245.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
349,15624,VPS,FL,Eglin AFB Destin Fort Walton Beach,Valparaiso,100k-1 million,no,loss,-1.4,less than -10%,...,2379.0,1994.0,1894.0,3676.0,3890.0,2253.0,1862.0,2553.0,2558.0,1733.0
350,15855,WST,RI,Westerly State,Westerly,10k-100k,no,loss,-10.5,at least -10%,...,1564.0,687.0,553.0,1116.0,1587.0,776.0,574.0,1010.0,1317.0,778.0
351,15919,XNA,AR,Northwest Arkansas National,Fayetteville,100k-1 million,no,loss,-22.4,at least -20%,...,1721.0,1781.0,1661.0,2447.0,2903.0,3273.0,2812.0,3128.0,3089.0,2960.0
352,16101,YKM,WA,Yakima Air Terminal/McAllister Field,Yakima,10k-100k,no,loss,-51.0,at least -30%,...,133.0,186.0,176.0,181.0,206.0,189.0,174.0,176.0,158.0,92.0
353,16869,XWA,ND,Williston Basin International,Williston,10k-100k,no,loss,-28.0,at least -20%,...,96.0,178.0,172.0,209.0,378.0,373.0,314.0,347.0,449.0,371.0

In [8]:
merged_df.to_csv('quarterly_deps_clusters_above10K.csv')